MvcBootcamp.Web/Controllers/CustomerAJAXController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NorthwindRepository.Repositories;

namespace MvcBootcamp.Web.Controllers
{
    public class CustomerAJAXController : Controller
    {

        private CustomerRepository custRepo = new CustomerRepository();        
        // GET: CustomerAJAX
        public ActionResult Index()
        {
            return View(custRepo.GetAllData().Take(10));
        }

        public ActionResult Search(string name)
        {
            var cust = custRepo.GetAllData().Where(c => c.CompanyName.Contains(name));

            if (Request.IsAjaxRequest())
            {
                return PartialView("_search", cust);
            }
            else
            {
                return View(cust);
            }
        }
    }
}

MvcBootcamp.Web/Views/CustomerAJAX/Index.cshtml
@model IEnumerable<DAL.Customer>

@{
    ViewBag.Title = "Customers AJAX";
}

<h2>@ViewBag.Title</h2>

<div>
    @using (Ajax.BeginForm("Search", "CustomerAJAX",
        new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "Get",
            UpdateTargetId = "divresult"
        }
        ))
        {
            <div class="form-group form-control">
                <input type="text" name="name" />
                <input type="submit" value="Search by AJAX" />
            </div>
        }
</div>

<div id="divresult">No Result</div>
<div>
    <ul>
        @foreach(var item in Model)
        {
            <li>
            @Ajax.ActionLink(item.CustomerID, "Search", new { name = item.CompanyName},
            new AjaxOptions
            {
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "Get",
                UpdateTargetId = "divdetails"
            })
            </li>
        }
    </ul>
</div>
<div id="divdetails">No Details</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryajax")    
}

MvcBootcamp.Web/Views/CustomerAJAX/Search.cshtml
@model IEnumerable<DAL.Customer>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>

            @Html.DisplayNameFor(model => model.CustomerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CustomerID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CustomerID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CustomerID })
        </td>
    </tr>
}

</table>

MvcBootcamp.Web/Views/CustomerAJAX/_search.cshtml
@model IEnumerable<DAL.Customer>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>

            @Html.DisplayNameFor(model => model.CustomerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CustomerID }) |
                @Html.ActionLink("Details", "Details", new { id = item.CustomerID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CustomerID })
            </td>
        </tr>
    }

</table>